spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}

    username: ${SPRING_DATASOURCE_USERNAME:postgres.ksmnsefgguukmfzdadcd}

    password: ${SPRING_DATASOURCE_PASSWORD:autowashcar123}

    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  health:
    redis:
      enabled: false
logging:
  level:
    com.autowash: DEBUG
    org.flywaydb: INFO

#  d6d0faa6-f06b-4935-99ab-78117de3f75a
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
